name: gst-build CI

on:
  pull_request:
    paths:
      - 'recipes/gst-build/all/**'
      - 'build.py'
      - '.github/workflows/gst-build.yml'
  push:
    branches:
      - master
    paths:
      - 'recipes/gst-build/all/**'
      - 'build.py'
      - '.github/workflows/gst-build.yml'

env:
  CONAN_PASSWORD: ${{ secrets.BintrayApiKey }}

jobs:
  gst-build:
    strategy:
      matrix:
        build: ['linux-gcc8']
        gst-build_versions: ['1.17.1']
        include:
          - build: 'linux-gcc8'
            os: 'ubuntu-latest'
            compiler: 'gcc'
            compiler_version: '8'
            docker_image: 'trassiross/conan-gcc8'
            build_types: 'Release'
            archs: 'x86_64'
            conan_options: '
              glib:with_pcre=False,
              glib:with_elf=False,
              glib:with_selinux=False,
              glib:with_mount=False
              '
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure git
        run: git config --global core.autocrlf false
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build and Optionally Upload
        uses: trassir/run-cpt@v0.2.2-trassir
        with:
          install: custom
          # TODO: replace when https://github.com/conan-io/conan-package-tools/issues/479 will be fixed upstream
          custom-package: git+https://github.com/trassir/conan-package-tools@fix-479-trassir
          work-dir: sources/recipes/gst-build/all
          build-script: ../../../build.py
          compiler: ${{ matrix.compiler }}
          compiler-versions: ${{ matrix.compiler_version }}
          docker-images: ${{ matrix.docker_image }}
        env:
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.deployment-target }}
          CONAN_VISUAL_RUNTIMES: ${{ matrix.vs_runtimes }}
          CONAN_ARCHS: ${{ matrix.archs }}
          CONAN_BUILD_TYPES: ${{ matrix.build_types }}
          CONAN_OPTIONS: ${{ matrix.conan_options }}
          CONAN_REFERENCE: gst-build/${{ matrix.gst-build_versions }}
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
